[package]
name = "rust-doc"
version = "0.1.0"
authors = ["徐鑫 <15204234251@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
